### ISSUE TITLE
One function question.

### ISSUE THREAD

**Issue by mobius07** [PortSwigger/param-miner#43] opened 2020-10-19 09:10 UTC
Hello.

Do you have an item in the menu that would add the found parameter to the sitemap? Those. I always send the found parameter from the scanner to the Repeater, and from there I add it to the sitemap. Maybe this function is, but I could not find it.

Thanks.

**Comment by albinowax** [comment] 2021-01-04 08:59
Dupe of https://github.com/PortSwigger/param-miner/issues/14

**Closed by albinowax** 2021-01-04 08:59 UTC
